on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: python -munittest
  push:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
          docker build . -t docker.pkg.github.com/${{ github.repository }}/test -t docker.pkg.github.com/${{ github.repository }}/test:${{ github.sha }}
          docker push docker.pkg.github.com/${{ github.repository }}/test
